base.url=https://accelerate-qa.calibo.com
login.url=https://accelerate-qa.calibo.com
username=api.automation@calibo.com
password=H2u82a^WA&jn
tenant.name=Automation
tenant.id=Tenant296388
headless=false
explicit.wait=60
retry.count=2
retry.interval=3000
test.data.path=src/test/resources/payloads/E2E/